### ISSUE TITLE
Why permission part corresponds to other action and even commented so there is no permission required for this librarian-only feature

### ISSUE THREAD

**Issue by rsolovev** [theMavl/LMS-Review#6]
https://github.com/theMavl/LMS-Review/blob/2edea403b71239ae415b0a37ed957458dd6c6880/library/views/document/renew_document.py#L14

**Comment by theMavl** [comment]
Renew directly changes GiveOut object (renews counter). Besides, permission decorator has been replaced with condition at https://github.com/theMavl/LMS-Review/blob/2edea403b71239ae415b0a37ed957458dd6c6880/library/views/document/renew_document.py#L18
since renewing was allowed for patron who booked this document.
